# Change these first
owner: spare-technologies # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Website
    url: https://tryspare.com
status-website:
  baseUrl: /status
  logoUrl: https://tryspare.com/assets/images/homepage/logo-blue.png
  name: Spare Status
  theme: ocean
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
