# Change these first
owner: spare-technologies # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Website
    url: https://tryspare.com
    assignees:
    - bdspare
    - hasnimehdi91
  - name: Docs
    url: https://docs.tryspare.com
    assignees:
    - bdspare
    - hasnimehdi91
  - name: Dashboard
    url: https://dashboard.tryspare.com
    assignees:
    - bdspare
    - hasnimehdi91
  - name: Dashboard(Sandbox)
    url: https://dashboard.sandbox.tryspare.com
    assignees:
    - bdspare
    - hasnimehdi91
status-website:
  baseUrl: /status
  logoUrl: https://tryspare.com/assets/images/homepage/logo-blue.png
  name: Status
  theme: light
  favicon: https://tryspare.com/assets/res/favicons/favicon-32x32.png
  robotsText: "User-agent: * \n Disallow: /"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
